name: Databricks CI

on:
  push:
    branches:
      - b
  pull_request:

jobs:
  databricks-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # This step checks out the repository code to the GitHub Actions runner.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      # This step sets up a Python 3.8 environment.

    - name: Install Databricks CLI
      run: pip install databricks-cli
      # This step installs the Databricks CLI using pip.

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF
      # This step configures the Databricks CLI using the host and token from GitHub Secrets.

    - name: Run Databricks Job
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        JOB_ID=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="your-job-name") | .job_id')
        databricks jobs run-now --job-id $JOB_ID
      # This step retrieves the job ID and runs the specified Databricks job.
